name: isu_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.5.4

dependencies:
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  file_picker: ^8.1.3
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  geolocator: ^13.0.1
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
